import { useEffect,useState } from "react";
import { Search, UserPlus, Receipt, Gift, History, RotateCcw, ArrowUpRight, Sparkles, QrCode } from "lucide-react";import {QRCodeCanvas} from "qrcode.react";
import api from "../api";
const tiers={Bronze:"tier-bronze",Silver:"tier-silver",Gold:"tier-gold",Platinum:"tier-platinum"};
export default function Counter(){
 const [phone,setPhone]=useState("");const [earnQR,setEarnQR]=useState(null);const [member,setMember]=useState(null);const [history,setHistory]=useState([]);const [rewards,setRewards]=useState([]);const [amount,setAmount]=useState("");const [name,setName]=useState("");const [enroll,setEnroll]=useState(false);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 const loadRewards=()=>api.get("/staff/rewards").then(r=>setRewards(r.data)); useEffect(()=>{loadRewards()},[]);
 async function lookup(e){e?.preventDefault();setMsg("");setMember(null);try{const {data}=await api.get("/staff/members/lookup",{params:{phone}});setMember(data);loadHistory(data.id)}catch(err){if(err.response?.status===404)setEnroll(true);else setMsg(err.response?.data?.error||"Lookup failed")}}
 async function loadHistory(id){const {data}=await api.get(`/staff/members/${id}/transactions`);setHistory(data)}
 async function createMember(e){e.preventDefault();try{const {data}=await api.post("/staff/members",{name,phone});setMember(data);setEnroll(false);setName("");loadHistory(data.id)}catch(err){setMsg(err.response?.data?.error||"Could not enroll")}}
 async function purchase(e){e.preventDefault();setBusy(true);setMsg("");try{const {data}=await api.post(`/staff/members/${member.id}/purchase`,{amountSpent:Number(amount)});setMember(data);setAmount("");loadHistory(member.id);setMsg(`Purchase recorded · ${data.currentBalance} points available`)}catch(err){setMsg(err.response?.data?.error||"Purchase failed")}finally{setBusy(false)}}
 async function redeem(id){setBusy(true);try{const {data}=await api.post(`/staff/members/${member.id}/redeem`,{rewardId:id});setMember(data);loadHistory(member.id);setMsg("Reward redeemed successfully")}catch(err){setMsg(err.response?.data?.error||"Redemption failed")}finally{setBusy(false)}}
 const reset=()=>{setPhone("");setMember(null);setHistory([]);setEnroll(false);setMsg("")};
 return <div><div className="page-head"><div><div className="eyebrow">POINT OF SALE</div><h1>Good afternoon 👋</h1><p>Look up a member, record a purchase and keep the relationship moving.</p></div><div className="live-pill"><span/> Live counter</div></div>
 <div className="counter-grid"><section className="card search-card"><div className="card-title"><div><h3>Find a customer</h3><p>Search by mobile number</p></div><Search size={20}/></div><form className="search-row" onSubmit={lookup}><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="e.g. 9000000001"/><button className="primary" type="submit"><Search size={17}/> Look up</button>{member&&<button className="icon-btn" type="button" onClick={reset}><RotateCcw size={17}/></button>}</form>{msg&&<div className={msg.includes("failed")||msg.includes("Could")?"alert error":"alert success"}>{msg}</div>}
 {enroll&&<form className="enroll" onSubmit={createMember}><UserPlus size={20}/><div><b>New customer</b><span>No member found for {phone}. Add them in seconds.</span></div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Customer name" required/><button className="secondary">Create</button></form>}
 {member&&<div className="member-hero"><div className="avatar">{member.name?.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div className="member-info"><div className="member-name">{member.name} <span className={`tier ${tiers[member.tier]}`}>{member.tier}</span></div><small>{member.phone}</small></div><div className="balance"><span>AVAILABLE</span><strong>{member.currentBalance.toLocaleString()}</strong><small>points</small></div></div>}
 {member&&<div className="quick-actions"><button className="secondary" onClick={async()=>{try{const{data}=await api.post("/staff/qr/earn",{memberId:member.id,points:100});setEarnQR(data)}catch(e){setMsg(e.response?.data?.error||"Could not create QR")}}}><QrCode size={16}/> Generate 100-point QR</button></div>}
 {earnQR&&<div className="earn-qr card"><div><b>Customer earn QR</b><span>Let the customer scan this QR to claim 100 points.</span><small>Expires {new Date(earnQR.expiresAt).toLocaleTimeString()}</small></div><QRCodeCanvas value={earnQR.token} size={120}/><button className="icon-btn" onClick={()=>setEarnQR(null)}>×</button></div>}
 {member&&<div className="mini-stats"><div><span>Lifetime earned</span><b>{member.lifetimePoints.toLocaleString()}</b></div><div><span>Current tier</span><b>{member.tier}</b></div><div><span>Next tier</span><b>{member.nextTier||"Max level"}</b></div></div>}</section>
 <section className="card purchase-card"><div className="card-title"><div><h3>Record purchase</h3><p>Points are calculated automatically</p></div><Receipt size={20}/></div>{member?<form onSubmit={purchase}><div className="money-input"><span>₹</span><input type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" required/></div><div className="earn-preview"><Sparkles size={16}/><span>Estimated points</span><b>{amount?Math.round(Number(amount)*(member.tier==="Platinum"?0.3:member.tier==="Gold"?1.5:member.tier==="Silver"?1.25:1)):0} pts</b></div><button className="primary full" disabled={busy}>{busy?"Processing…":"Add points"}<ArrowUpRight size={17}/></button></form>:<div className="empty-state"><Receipt size={32}/><b>Select a customer first</b><span>Find a member on the left to record their purchase.</span></div>}</section></div>
 {member&&<div className="two-col"><section className="card"><div className="card-title"><div><h3>Rewards</h3><p>Available for this customer</p></div><Gift size={20}/></div><div className="reward-grid">{rewards.map(r=><div className="reward" key={r._id}><div className="reward-icon"><Gift size={17}/></div><div><b>{r.name}</b><span>{r.pointsCost} points</span></div><button disabled={member.currentBalance<r.pointsCost||busy} onClick={()=>redeem(r._id)}>Redeem</button></div>)}</div></section><section className="card"><div className="card-title"><div><h3>Recent activity</h3><p>Latest 50 ledger entries</p></div><History size={20}/></div><div className="activity">{history.length?history.slice(0,7).map(t=><div className="activity-row" key={t._id}><div className={`activity-dot ${t.type}`}>{t.type==="purchase"?"+":"−"}</div><div><b>{t.type==="purchase"?"Purchase":t.type==="bonus"?"Referral bonus":"Reward redemption"}</b><span>{t.type==="purchase"?`₹${t.amountSpent} spent`:t.type==="bonus"?"Referral reward":`${t.reward?.name||"Reward"}`}</span></div><strong className={t.type==="purchase"?"positive":"negative"}>{t.type==="redemption"?`-${t.pointsSpent}`:`+${t.pointsEarned}`} pts</strong></div>):<div className="empty-state"><History size={28}/><span>No activity yet.</span></div>}</div></section></div>}
 </div>;
}
