import { useState } from "react";
import { Coffee, LockKeyhole, Mail, ArrowRight, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Login(){
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const {login}=useAuth(); const navigate=useNavigate();
 async function submit(e){e.preventDefault();setError("");setBusy(true);try{const u=await login(email,password);navigate(u.role==="admin"?"/admin":"/staff")}catch(err){setError(err.response?.data?.error||"Unable to sign in")}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-visual"><div className="visual-noise"/><div className="visual-content"><div className="brand light"><div className="brand-mark"><Coffee size={22}/></div><div><strong>CafePoints</strong><span>LOYALTY OS</span></div></div><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> SMARTER CUSTOMER RETENTION</div><h1>Turn every visit into a <em>relationship.</em></h1><p>One beautiful workspace for points, rewards, customer profiles and everyday café operations.</p></div><div className="quote">“Simple for staff. Delightful for customers.”</div></div></div>
 <div className="login-card-wrap"><div className="login-card"><div className="mobile-logo"><Coffee size={20}/><b>CafePoints</b></div><div className="login-heading"><span className="eyebrow">STAFF ACCESS</span><h2>Welcome back</h2><p>Sign in to manage today's loyalty activity.</p></div><form onSubmit={submit}><label>Email<div className="input-wrap"><Mail size={17}/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@cafe.com" required/></div></label><label>Password<div className="input-wrap"><LockKeyhole size={17}/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="••••••••" required/></div></label>{error&&<div className="alert error">{error}</div>}<button className="primary full" disabled={busy}>{busy?"Signing in…":"Sign in"}<ArrowRight size={17}/></button></form><div className="demo-box"><b>Demo access</b><span>admin@demo.local · password123</span><span>staff@demo.local · password123</span></div><p className="login-foot">Customer? <a href="/customer">Open the customer portal →</a></p></div></div></div>
}
